# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  blazor:
    image: chessy-blazor
    build:
      context: .
      dockerfile: src/Chessy.Blazor/Dockerfile
    ports:
      - 8080:8080
    #platform: linux/arm64

  wasm:
    image: chessy-wasm
    build:
      context: .
      dockerfile: src/Chessy.BlazorWasm/Dockerfile
    ports:
      - 8081:8080
    environment:
      - NGINX_PORT=8080

  console:
    image: chessy-console
    build:
      context: .
      dockerfile: src/Chessy.Console/Dockerfile

  benchmarks:
    image: chessy-benchmarks
    build:
      context: .
      dockerfile: tests/Chessy.Benchmarks/Dockerfile

  engine-tests:
    image: chessy-engine-tests
    build:
      context: .
      dockerfile: tests/Chessy.Engine.Tests/Dockerfile
