# fly.toml app configuration file generated for chessy-blaz on 2024-04-11T00:08:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chessy-blaz'
primary_region = 'waw'

[build]
  dockerfile = 'Chessy.Blazor/Dockerfile'

[http_service]
  internal_port = 5083
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
